spring:
  mail:
    username: jijuwoi@naver.com
    password: PTMRGS47VPKN

kakao:
  jsKey: "7860854fd6e8b88d76dd14c9f65cb678"
  mobilityRestKey: "74078def9edc471310ea8278ef444d37"

cloud:
  ncp:
    storage:
      access-key: ncp_iam_BPASKR5Swoefh9vLKMB5
      secret-key: ncp_iam_BPKSKR6TPh9YAHltc0vCtk0et6w148xbuy
